# Generated by Django 4.0.5 on 2022-06-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='job title', max_length=100)),
                ('job_description', models.TextField()),
                ('job_vacancy', models.IntegerField()),
                ('job_location', models.CharField(max_length=100)),
                ('working_days', models.IntegerField()),
                ('working_hours', models.IntegerField()),
                ('job_type', models.CharField(max_length=50)),
                ('job_industry', models.CharField(max_length=50)),
                ('salary_expectation', models.IntegerField()),
                ('job_pay_rate_type', models.CharField(max_length=100)),
                ('required_job_experince', models.IntegerField()),
                ('require_job_skill', models.CharField(max_length=100)),
            ],
        ),
    ]
