# Generated by Django 4.0.5 on 2022-08-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(default=None)),
                ('job_bot', models.CharField(max_length=100)),
                ('job_title', models.CharField(default='job title', max_length=100)),
                ('job_location', models.CharField(max_length=200)),
                ('working_hours', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default='Choose an option')),
                ('job_description', models.TextField()),
                ('job_vacancy', models.IntegerField()),
                ('job_type', models.CharField(choices=[('Freelancing', 'Freelancing'), ('Contactual', 'Contactual'), ('empolyee', 'As an regular empolyee'), ('Other', 'Others')], default='Choose an option', max_length=50)),
                ('job_industry', models.CharField(choices=[('IT', 'IT'), ('Automobile', 'Automobile'), ('Corporate', 'Corporate'), ('Bank', 'Bank')], default='Choose an option', max_length=50)),
                ('max_salary', models.IntegerField()),
                ('min_salary', models.IntegerField()),
                ('job_pay_rate_type', models.CharField(choices=[('Freelancing', 'Freelancing'), ('Contactual', 'Contactual'), ('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Yearly', 'Yearly')], default='Choose an option', max_length=100)),
                ('required_job_experince', models.IntegerField(choices=[(1, '1 years'), (2, '2 years'), (3, '3 years'), (4, '4 years'), (5, '5+ years '), (10, '10+ years ')], default='Choose an option')),
                ('require_job_skill', models.CharField(choices=[('get_ui_designer', 'Ui designer'), ('developer', ' Developer'), ('site_engineer', 'site engineer')], default='Choose an option', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BotManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subcriptionPlan', models.IntegerField()),
                ('botsIds', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='BotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botName', models.CharField(max_length=200)),
                ('adsIds', models.CharField(max_length=10000)),
            ],
        ),
    ]
