# Generated by Django 4.0.5 on 2022-08-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admodel',
            name='job_bot',
        ),
    ]
