# Generated by Django 4.0.5 on 2022-08-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0002_remove_admodel_job_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='admodel',
            name='job_bot',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
