# Generated by Django 4.0.5 on 2022-08-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0003_admodel_job_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedJobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(default=None)),
                ('job_title', models.CharField(max_length=200)),
                ('applicient_email_or_phone', models.CharField(max_length=100)),
            ],
        ),
    ]
