# Generated by Django 4.0.5 on 2022-08-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0004_submittedjobapplications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedjobapplications',
            name='applicient_email_or_phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
