# Generated by Django 4.0.5 on 2022-08-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0005_alter_submittedjobapplications_applicient_email_or_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admodel',
            old_name='job_bot',
            new_name='job_manager',
        ),
    ]
