# Generated by Django 4.0.5 on 2022-08-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0007_botmanager_manageradsids'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedjobapplications',
            name='job_manger',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
