# Generated by Django 4.0.5 on 2022-08-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmanager', '0009_rename_job_manger_submittedjobapplications_job_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='botManagerName',
            field=models.CharField(default='Unknwon', max_length=200),
        ),
        migrations.AlterField(
            model_name='botmanager',
            name='ManagerAdsIds',
            field=models.CharField(max_length=10000),
        ),
    ]
